### PR TITLE
added cool file :)

### PR DESCRIPTION
**Pull request by fernandeeees**

### CODE REVIEW

**Comment by fernandeeees** [comment]
:))))))

**Comment by Francisca105** [comment]
Não funciona

**Comment by SrGesus** [comment]
está bugado

**Comment by Francisca105** [comment]
@Scuffedwrldwide resolve

**Comment by SrGesus** [comment]
@Scuffedwrldwide delete your account

**Comment by fernandeeees** [comment]
fixed!!

**Comment by Margarida-Lourenco** [comment]
??

**Review by SrGesus — COMMENTED** [review]
This is trash who made this, it's just a fork bomb

**Review by SrGesus — CHANGES_REQUESTED** [review]
Please add documentation

**Review by SrGesus — APPROVED** [review]
Very nice!

**Pull request merged**
